export const wifiCountries = [
    { code: 'AD', name: 'Andorra' },
    { code: 'AE', name: 'United Arab Emirates' },
    { code: 'AF', name: 'Afghanistan' },
    { code: 'AG', name: 'Antigua & Barbuda' },
    { code: 'AI', name: 'Anguilla' },
    { code: 'AL', name: 'Albania' },
    { code: 'AM', name: 'Armenia' },
    { code: 'AO', name: 'Angola' },
    { code: 'AQ', name: 'Antarctica' },
    { code: 'AR', name: 'Argentina' },
    { code: 'AS', name: 'Samoa (American)' },
    { code: 'AT', name: 'Austria' },
    { code: 'AU', name: 'Australia' },
    { code: 'AW', name: 'Aruba' },
    { code: 'AX', name: 'Åland Islands' },
    { code: 'AZ', name: 'Azerbaijan' },
    { code: 'BA', name: 'Bosnia & Herzegovina' },
    { code: 'BB', name: 'Barbados' },
    { code: 'BD', name: 'Bangladesh' },
    { code: 'BE', name: 'Belgium' },
    { code: 'BF', name: 'Burkina Faso' },
    { code: 'BG', name: 'Bulgaria' },
    { code: 'BH', name: 'Bahrain' },
    { code: 'BI', name: 'Burundi' },
    { code: 'BJ', name: 'Benin' },
    { code: 'BL', name: 'St Barthelemy' },
    { code: 'BM', name: 'Bermuda' },
    { code: 'BN', name: 'Brunei' },
    { code: 'BO', name: 'Bolivia' },
    { code: 'BQ', name: 'Caribbean NL' },
    { code: 'BR', name: 'Brazil' },
    { code: 'BS', name: 'Bahamas' },
    { code: 'BT', name: 'Bhutan' },
    { code: 'BV', name: 'Bouvet Island' },
    { code: 'BW', name: 'Botswana' },
    { code: 'BY', name: 'Belarus' },
    { code: 'BZ', name: 'Belize' },
    { code: 'CA', name: 'Canada' },
    { code: 'CC', name: 'Cocos (Keeling) Islands' },
    { code: 'CD', name: 'Congo (Dem. Rep.)' },
    { code: 'CF', name: 'Central African Rep.' },
    { code: 'CG', name: 'Congo (Rep.)' },
    { code: 'CH', name: 'Switzerland' },
    { code: 'CI', name: 'Côte d\'Ivoire' },
    { code: 'CK', name: 'Cook Islands' },
    { code: 'CL', name: 'Chile' },
    { code: 'CM', name: 'Cameroon' },
    { code: 'CN', name: 'China' },
    { code: 'CO', name: 'Colombia' },
    { code: 'CR', name: 'Costa Rica' },
    { code: 'CU', name: 'Cuba' },
    { code: 'CV', name: 'Cape Verde' },
    { code: 'CW', name: 'Curaçao' },
    { code: 'CX', name: 'Christmas Island' },
    { code: 'CY', name: 'Cyprus' },
    { code: 'CZ', name: 'Czech Republic' },
    { code: 'DE', name: 'Germany' },
    { code: 'DJ', name: 'Djibouti' },
    { code: 'DK', name: 'Denmark' },
    { code: 'DM', name: 'Dominica' },
    { code: 'DO', name: 'Dominican Republic' },
    { code: 'DZ', name: 'Algeria' },
    { code: 'EC', name: 'Ecuador' },
    { code: 'EE', name: 'Estonia' },
    { code: 'EG', name: 'Egypt' },
    { code: 'EH', name: 'Western Sahara' },
    { code: 'ER', name: 'Eritrea' },
    { code: 'ES', name: 'Spain' },
    { code: 'ET', name: 'Ethiopia' },
    { code: 'FI', name: 'Finland' },
    { code: 'FJ', name: 'Fiji' },
    { code: 'FK', name: 'Falkland Islands' },
    { code: 'FM', name: 'Micronesia' },
    { code: 'FO', name: 'Faroe Islands' },
    { code: 'FR', name: 'France' },
    { code: 'GA', name: 'Gabon' },
    { code: 'GB', name: 'Britain (UK)' },
    { code: 'GD', name: 'Grenada' },
    { code: 'GE', name: 'Georgia' },
    { code: 'GF', name: 'French Guiana' },
    { code: 'GG', name: 'Guernsey' },
    { code: 'GH', name: 'Ghana' },
    { code: 'GI', name: 'Gibraltar' },
    { code: 'GL', name: 'Greenland' },
    { code: 'GM', name: 'Gambia' },
    { code: 'GN', name: 'Guinea' },
    { code: 'GP', name: 'Guadeloupe' },
    { code: 'GQ', name: 'Equatorial Guinea' },
    { code: 'GR', name: 'Greece' },
    { code: 'GS', name: 'South Georgia & the South Sandwich Islands' },
    { code: 'GT', name: 'Guatemala' },
    { code: 'GU', name: 'Guam' },
    { code: 'GW', name: 'Guinea-Bissau' },
    { code: 'GY', name: 'Guyana' },
    { code: 'HK', name: 'Hong Kong' },
    { code: 'HM', name: 'Heard Island & McDonald Islands' },
    { code: 'HN', name: 'Honduras' },
    { code: 'HR', name: 'Croatia' },
    { code: 'HT', name: 'Haiti' },
    { code: 'HU', name: 'Hungary' },
    { code: 'ID', name: 'Indonesia' },
    { code: 'IE', name: 'Ireland' },
    { code: 'IL', name: 'Israel' },
    { code: 'IM', name: 'Isle of Man' },
    { code: 'IN', name: 'India' },
    { code: 'IO', name: 'British Indian Ocean Territory' },
    { code: 'IQ', name: 'Iraq' },
    { code: 'IR', name: 'Iran' },
    { code: 'IS', name: 'Iceland' },
    { code: 'IT', name: 'Italy' },
    { code: 'JE', name: 'Jersey' },
    { code: 'JM', name: 'Jamaica' },
    { code: 'JO', name: 'Jordan' },
    { code: 'JP', name: 'Japan' },
    { code: 'KE', name: 'Kenya' },
    { code: 'KG', name: 'Kyrgyzstan' },
    { code: 'KH', name: 'Cambodia' },
    { code: 'KI', name: 'Kiribati' },
    { code: 'KM', name: 'Comoros' },
    { code: 'KN', name: 'St Kitts & Nevis' },
    { code: 'KP', name: 'Korea (North)' },
    { code: 'KR', name: 'Korea (South)' },
    { code: 'KW', name: 'Kuwait' },
    { code: 'KY', name: 'Cayman Islands' },
    { code: 'KZ', name: 'Kazakhstan' },
    { code: 'LA', name: 'Laos' },
    { code: 'LB', name: 'Lebanon' },
    { code: 'LC', name: 'St Lucia' },
    { code: 'LI', name: 'Liechtenstein' },
    { code: 'LK', name: 'Sri Lanka' },
    { code: 'LR', name: 'Liberia' },
    { code: 'LS', name: 'Lesotho' },
    { code: 'LT', name: 'Lithuania' },
    { code: 'LU', name: 'Luxembourg' },
    { code: 'LV', name: 'Latvia' },
    { code: 'LY', name: 'Libya' },
    { code: 'MA', name: 'Morocco' },
    { code: 'MC', name: 'Monaco' },
    { code: 'MD', name: 'Moldova' },
    { code: 'ME', name: 'Montenegro' },
    { code: 'MF', name: 'St Martin (French)' },
    { code: 'MG', name: 'Madagascar' },
    { code: 'MH', name: 'Marshall Islands' },
    { code: 'MK', name: 'North Macedonia' },
    { code: 'ML', name: 'Mali' },
    { code: 'MM', name: 'Myanmar (Burma)' },
    { code: 'MN', name: 'Mongolia' },
    { code: 'MO', name: 'Macau' },
    { code: 'MP', name: 'Northern Mariana Islands' },
    { code: 'MQ', name: 'Martinique' },
    { code: 'MR', name: 'Mauritania' },
    { code: 'MS', name: 'Montserrat' },
    { code: 'MT', name: 'Malta' },
    { code: 'MU', name: 'Mauritius' },
    { code: 'MV', name: 'Maldives' },
    { code: 'MW', name: 'Malawi' },
    { code: 'MX', name: 'Mexico' },
    { code: 'MY', name: 'Malaysia' },
    { code: 'MZ', name: 'Mozambique' },
    { code: 'NA', name: 'Namibia' },
    { code: 'NC', name: 'New Caledonia' },
    { code: 'NE', name: 'Niger' },
    { code: 'NF', name: 'Norfolk Island' },
    { code: 'NG', name: 'Nigeria' },
    { code: 'NI', name: 'Nicaragua' },
    { code: 'NL', name: 'Netherlands' },
    { code: 'NO', name: 'Norway' },
    { code: 'NP', name: 'Nepal' },
    { code: 'NR', name: 'Nauru' },
    { code: 'NU', name: 'Niue' },
    { code: 'NZ', name: 'New Zealand' },
    { code: 'OM', name: 'Oman' },
    { code: 'PA', name: 'Panama' },
    { code: 'PE', name: 'Peru' },
    { code: 'PF', name: 'French Polynesia' },
    { code: 'PG', name: 'Papua New Guinea' },
    { code: 'PH', name: 'Philippines' },
    { code: 'PK', name: 'Pakistan' },
    { code: 'PL', name: 'Poland' },
    { code: 'PM', name: 'St Pierre & Miquelon' },
    { code: 'PN', name: 'Pitcairn' },
    { code: 'PR', name: 'Puerto Rico' },
    { code: 'PS', name: 'Palestine' },
    { code: 'PT', name: 'Portugal' },
    { code: 'PW', name: 'Palau' },
    { code: 'PY', name: 'Paraguay' },
    { code: 'QA', name: 'Qatar' },
    { code: 'RE', name: 'Réunion' },
    { code: 'RO', name: 'Romania' },
    { code: 'RS', name: 'Serbia' },
    { code: 'RU', name: 'Russia' },
    { code: 'RW', name: 'Rwanda' },
    { code: 'SA', name: 'Saudi Arabia' },
    { code: 'SB', name: 'Solomon Islands' },
    { code: 'SC', name: 'Seychelles' },
    { code: 'SD', name: 'Sudan' },
    { code: 'SE', name: 'Sweden' },
    { code: 'SG', name: 'Singapore' },
    { code: 'SH', name: 'St Helena' },
    { code: 'SI', name: 'Slovenia' },
    { code: 'SJ', name: 'Svalbard & Jan Mayen' },
    { code: 'SK', name: 'Slovakia' },
    { code: 'SL', name: 'Sierra Leone' },
    { code: 'SM', name: 'San Marino' },
    { code: 'SN', name: 'Senegal' },
    { code: 'SO', name: 'Somalia' },
    { code: 'SR', name: 'Suriname' },
    { code: 'SS', name: 'South Sudan' },
    { code: 'ST', name: 'Sao Tome & Principe' },
    { code: 'SV', name: 'El Salvador' },
    { code: 'SX', name: 'St Maarten (Dutch)' },
    { code: 'SY', name: 'Syria' },
    { code: 'SZ', name: 'Eswatini (Swaziland)' },
    { code: 'TC', name: 'Turks & Caicos Is' },
    { code: 'TD', name: 'Chad' },
    { code: 'TF', name: 'French S. Terr.' },
    { code: 'TG', name: 'Togo' },
    { code: 'TH', name: 'Thailand' },
    { code: 'TJ', name: 'Tajikistan' },
    { code: 'TK', name: 'Tokelau' },
    { code: 'TL', name: 'East Timor' },
    { code: 'TM', name: 'Turkmenistan' },
    { code: 'TN', name: 'Tunisia' },
    { code: 'TO', name: 'Tonga' },
    { code: 'TR', name: 'Turkey' },
    { code: 'TT', name: 'Trinidad & Tobago' },
    { code: 'TV', name: 'Tuvalu' },
    { code: 'TW', name: 'Taiwan' },
    { code: 'TZ', name: 'Tanzania' },
    { code: 'UA', name: 'Ukraine' },
    { code: 'UG', name: 'Uganda' },
    { code: 'UM', name: 'US minor outlying islands' },
    { code: 'US', name: 'United States' },
    { code: 'UY', name: 'Uruguay' },
    { code: 'UZ', name: 'Uzbekistan' },
    { code: 'VA', name: 'Vatican City' },
    { code: 'VC', name: 'St Vincent' },
    { code: 'VE', name: 'Venezuela' },
    { code: 'VG', name: 'Virgin Islands (UK)' },
    { code: 'VI', name: 'Virgin Islands (US)' },
    { code: 'VN', name: 'Vietnam' },
    { code: 'VU', name: 'Vanuatu' },
    { code: 'WF', name: 'Wallis & Futuna' },
    { code: 'WS', name: 'Samoa (western)' },
    { code: 'YE', name: 'Yemen' },
    { code: 'YT', name: 'Mayotte' },
    { code: 'ZA', name: 'South Africa' },
    { code: 'ZM', name: 'Zambia' },
    { code: 'ZW', name: 'Zimbabwe' },
];

export const timezones = [
    { value: 'Africa/Abidjan', label: 'Africa/Abidjan' },
    { value: 'Africa/Accra', label: 'Africa/Accra' },
    { value: 'Africa/Addis_Ababa', label: 'Africa/Addis_Ababa' },
    { value: 'Africa/Algiers', label: 'Africa/Algiers' },
    { value: 'Africa/Asmara', label: 'Africa/Asmara' },
    { value: 'Africa/Bamako', label: 'Africa/Bamako' },
    { value: 'Africa/Bangui', label: 'Africa/Bangui' },
    { value: 'Africa/Banjul', label: 'Africa/Banjul' },
    { value: 'Africa/Bissau', label: 'Africa/Bissau' },
    { value: 'Africa/Blantyre', label: 'Africa/Blantyre' },
    { value: 'Africa/Brazzaville', label: 'Africa/Brazzaville' },
    { value: 'Africa/Bujumbura', label: 'Africa/Bujumbura' },
    { value: 'Africa/Cairo', label: 'Africa/Cairo' },
    { value: 'Africa/Casablanca', label: 'Africa/Casablanca' },
    { value: 'Africa/Ceuta', label: 'Africa/Ceuta' },
    { value: 'Africa/Conakry', label: 'Africa/Conakry' },
    { value: 'Africa/Dakar', label: 'Africa/Dakar' },
    { value: 'Africa/Dar_es_Salaam', label: 'Africa/Dar_es_Salaam' },
    { value: 'Africa/Djibouti', label: 'Africa/Djibouti' },
    { value: 'Africa/Douala', label: 'Africa/Douala' },
    { value: 'Africa/El_Aaiun', label: 'Africa/El_Aaiun' },
    { value: 'Africa/Freetown', label: 'Africa/Freetown' },
    { value: 'Africa/Gaborone', label: 'Africa/Gaborone' },
    { value: 'Africa/Harare', label: 'Africa/Harare' },
    { value: 'Africa/Johannesburg', label: 'Africa/Johannesburg' },
    { value: 'Africa/Juba', label: 'Africa/Juba' },
    { value: 'Africa/Kampala', label: 'Africa/Kampala' },
    { value: 'Africa/Khartoum', label: 'Africa/Khartoum' },
    { value: 'Africa/Kigali', label: 'Africa/Kigali' },
    { value: 'Africa/Kinshasa', label: 'Africa/Kinshasa' },
    { value: 'Africa/Lagos', label: 'Africa/Lagos' },
    { value: 'Africa/Libreville', label: 'Africa/Libreville' },
    { value: 'Africa/Lome', label: 'Africa/Lome' },
    { value: 'Africa/Luanda', label: 'Africa/Luanda' },
    { value: 'Africa/Lubumbashi', label: 'Africa/Lubumbashi' },
    { value: 'Africa/Lusaka', label: 'Africa/Lusaka' },
    { value: 'Africa/Malabo', label: 'Africa/Malabo' },
    { value: 'Africa/Maputo', label: 'Africa/Maputo' },
    { value: 'Africa/Maseru', label: 'Africa/Maseru' },
    { value: 'Africa/Mbabane', label: 'Africa/Mbabane' },
    { value: 'Africa/Mogadishu', label: 'Africa/Mogadishu' },
    { value: 'Africa/Monrovia', label: 'Africa/Monrovia' },
    { value: 'Africa/Nairobi', label: 'Africa/Nairobi' },
    { value: 'Africa/Ndjamena', label: 'Africa/Ndjamena' },
    { value: 'Africa/Niamey', label: 'Africa/Niamey' },
    { value: 'Africa/Nouakchott', label: 'Africa/Nouakchott' },
    { value: 'Africa/Ouagadougou', label: 'Africa/Ouagadougou' },
    { value: 'Africa/Porto-Novo', label: 'Africa/Porto-Novo' },
    { value: 'Africa/Sao_Tome', label: 'Africa/Sao_Tome' },
    { value: 'Africa/Tripoli', label: 'Africa/Tripoli' },
    { value: 'Africa/Tunis', label: 'Africa/Tunis' },
    { value: 'Africa/Windhoek', label: 'Africa/Windhoek' },
    { value: 'America/Adak', label: 'America/Adak' },
    { value: 'America/Anchorage', label: 'America/Anchorage' },
    { value: 'America/Anguilla', label: 'America/Anguilla' },
    { value: 'America/Antigua', label: 'America/Antigua' },
    { value: 'America/Araguaina', label: 'America/Araguaina' },
    { value: 'America/Argentina/Buenos_Aires', label: 'America/Argentina/Buenos_Aires' },
    { value: 'America/Argentina/Catamarca', label: 'America/Argentina/Catamarca' },
    { value: 'America/Argentina/Cordoba', label: 'America/Argentina/Cordoba' },
    { value: 'America/Argentina/Jujuy', label: 'America/Argentina/Jujuy' },
    { value: 'America/Argentina/La_Rioja', label: 'America/Argentina/La_Rioja' },
    { value: 'America/Argentina/Mendoza', label: 'America/Argentina/Mendoza' },
    { value: 'America/Argentina/Rio_Gallegos', label: 'America/Argentina/Rio_Gallegos' },
    { value: 'America/Argentina/Salta', label: 'America/Argentina/Salta' },
    { value: 'America/Argentina/San_Juan', label: 'America/Argentina/San_Juan' },
    { value: 'America/Argentina/San_Luis', label: 'America/Argentina/San_Luis' },
    { value: 'America/Argentina/Tucuman', label: 'America/Argentina/Tucuman' },
    { value: 'America/Argentina/Ushuaia', label: 'America/Argentina/Ushuaia' },
    { value: 'America/Aruba', label: 'America/Aruba' },
    { value: 'America/Asuncion', label: 'America/Asuncion' },
    { value: 'America/Atikokan', label: 'America/Atikokan' },
    { value: 'America/Bahia', label: 'America/Bahia' },
    { value: 'America/Bahia_Banderas', label: 'America/Bahia_Banderas' },
    { value: 'America/Barbados', label: 'America/Barbados' },
    { value: 'America/Belem', label: 'America/Belem' },
    { value: 'America/Belize', label: 'America/Belize' },
    { value: 'America/Blanc-Sablon', label: 'America/Blanc-Sablon' },
    { value: 'America/Boa_Vista', label: 'America/Boa_Vista' },
    { value: 'America/Bogota', label: 'America/Bogota' },
    { value: 'America/Boise', label: 'America/Boise' },
    { value: 'America/Cambridge_Bay', label: 'America/Cambridge_Bay' },
    { value: 'America/Campo_Grande', label: 'America/Campo_Grande' },
    { value: 'America/Cancun', label: 'America/Cancun' },
    { value: 'America/Caracas', label: 'America/Caracas' },
    { value: 'America/Cayenne', label: 'America/Cayenne' },
    { value: 'America/Cayman', label: 'America/Cayman' },
    { value: 'America/Chicago', label: 'America/Chicago' },
    { value: 'America/Chihuahua', label: 'America/Chihuahua' },
    { value: 'America/Costa_Rica', label: 'America/Costa_Rica' },
    { value: 'America/Creston', label: 'America/Creston' },
    { value: 'America/Cuiaba', label: 'America/Cuiaba' },
    { value: 'America/Curacao', label: 'America/Curacao' },
    { value: 'America/Danmarkshavn', label: 'America/Danmarkshavn' },
    { value: 'America/Dawson', label: 'America/Dawson' },
    { value: 'America/Dawson_Creek', label: 'America/Dawson_Creek' },
    { value: 'America/Denver', label: 'America/Denver' },
    { value: 'America/Detroit', label: 'America/Detroit' },
    { value: 'America/Dominica', label: 'America/Dominica' },
    { value: 'America/Edmonton', label: 'America/Edmonton' },
    { value: 'America/Eirunepe', label: 'America/Eirunepe' },
    { value: 'America/El_Salvador', label: 'America/El_Salvador' },
    { value: 'America/Fort_Nelson', label: 'America/Fort_Nelson' },
    { value: 'America/Fortaleza', label: 'America/Fortaleza' },
    { value: 'America/Glace_Bay', label: 'America/Glace_Bay' },
    { value: 'America/Godthab', label: 'America/Godthab' },
    { value: 'America/Goose_Bay', label: 'America/Goose_Bay' },
    { value: 'America/Grand_Turk', label: 'America/Grand_Turk' },
    { value: 'America/Grenada', label: 'America/Grenada' },
    { value: 'America/Guadeloupe', label: 'America/Guadeloupe' },
    { value: 'America/Guatemala', label: 'America/Guatemala' },
    { value: 'America/Guayaquil', label: 'America/Guayaquil' },
    { value: 'America/Guyana', label: 'America/Guyana' },
    { value: 'America/Halifax', label: 'America/Halifax' },
    { value: 'America/Havana', label: 'America/Havana' },
    { value: 'America/Hermosillo', label: 'America/Hermosillo' },
    { value: 'America/Indiana/Indianapolis', label: 'America/Indiana/Indianapolis' },
    { value: 'America/Indiana/Knox', label: 'America/Indiana/Knox' },
    { value: 'America/Indiana/Marengo', label: 'America/Indiana/Marengo' },
    { value: 'America/Indiana/Petersburg', label: 'America/Indiana/Petersburg' },
    { value: 'America/Indiana/Tell_City', label: 'America/Indiana/Tell_City' },
    { value: 'America/Indiana/Vevay', label: 'America/Indiana/Vevay' },
    { value: 'America/Indiana/Vincennes', label: 'America/Indiana/Vincennes' },
    { value: 'America/Indiana/Winamac', label: 'America/Indiana/Winamac' },
    { value: 'America/Inuvik', label: 'America/Inuvik' },
    { value: 'America/Iqaluit', label: 'America/Iqaluit' },
    { value: 'America/Jamaica', label: 'America/Jamaica' },
    { value: 'America/Juneau', label: 'America/Juneau' },
    { value: 'America/Kentucky/Louisville', label: 'America/Kentucky/Louisville' },
    { value: 'America/Kentucky/Monticello', label: 'America/Kentucky/Monticello' },
    { value: 'America/Kralendijk', label: 'America/Kralendijk' },
    { value: 'America/La_Paz', label: 'America/La_Paz' },
    { value: 'America/Lima', label: 'America/Lima' },
    { value: 'America/Los_Angeles', label: 'America/Los_Angeles' },
    { value: 'America/Lower_Princes', label: 'America/Lower_Princes' },
    { value: 'America/Maceio', label: 'America/Maceio' },
    { value: 'America/Managua', label: 'America/Managua' },
    { value: 'America/Manaus', label: 'America/Manaus' },
    { value: 'America/Marigot', label: 'America/Marigot' },
    { value: 'America/Martinique', label: 'America/Martinique' },
    { value: 'America/Matamoros', label: 'America/Matamoros' },
    { value: 'America/Mazatlan', label: 'America/Mazatlan' },
    { value: 'America/Menominee', label: 'America/Menominee' },
    { value: 'America/Merida', label: 'America/Merida' },
    { value: 'America/Metlakatla', label: 'America/Metlakatla' },
    { value: 'America/Mexico_City', label: 'America/Mexico_City' },
    { value: 'America/Miquelon', label: 'America/Miquelon' },
    { value: 'America/Moncton', label: 'America/Moncton' },
    { value: 'America/Monterrey', label: 'America/Monterrey' },
    { value: 'America/Montevideo', label: 'America/Montevideo' },
    { value: 'America/Montserrat', label: 'America/Montserrat' },
    { value: 'America/Nassau', label: 'America/Nassau' },
    { value: 'America/New_York', label: 'America/New_York' },
    { value: 'America/Nipigon', label: 'America/Nipigon' },
    { value: 'America/Nome', label: 'America/Nome' },
    { value: 'America/Noronha', label: 'America/Noronha' },
    { value: 'America/North_Dakota/Beulah', label: 'America/North_Dakota/Beulah' },
    { value: 'America/North_Dakota/Center', label: 'America/North_Dakota/Center' },
    { value: 'America/North_Dakota/New_Salem', label: 'America/North_Dakota/New_Salem' },
    { value: 'America/Ojinaga', label: 'America/Ojinaga' },
    { value: 'America/Panama', label: 'America/Panama' },
    { value: 'America/Pangnirtung', label: 'America/Pangnirtung' },
    { value: 'America/Paramaribo', label: 'America/Paramaribo' },
    { value: 'America/Phoenix', label: 'America/Phoenix' },
    { value: 'America/Port-au-Prince', label: 'America/Port-au-Prince' },
    { value: 'America/Port_of_Spain', label: 'America/Port_of_Spain' },
    { value: 'America/Porto_Velho', label: 'America/Porto_Velho' },
    { value: 'America/Puerto_Rico', label: 'America/Puerto_Rico' },
    { value: 'America/Punta_Arenas', label: 'America/Punta_Arenas' },
    { value: 'America/Rainy_River', label: 'America/Rainy_River' },
    { value: 'America/Rankin_Inlet', label: 'America/Rankin_Inlet' },
    { value: 'America/Recife', label: 'America/Recife' },
    { value: 'America/Regina', label: 'America/Regina' },
    { value: 'America/Resolute', label: 'America/Resolute' },
    { value: 'America/Rio_Branco', label: 'America/Rio_Branco' },
    { value: 'America/Santa_Isabel', label: 'America/Santa_Isabel' },
    { value: 'America/Santarem', label: 'America/Santarem' },
    { value: 'America/Santiago', label: 'America/Santiago' },
    { value: 'America/Santo_Domingo', label: 'America/Santo_Domingo' },
    { value: 'America/Sao_Paulo', label: 'America/Sao_Paulo' },
    { value: 'America/Scoresbysund', label: 'America/Scoresbysund' },
    { value: 'America/Sitka', label: 'America/Sitka' },
    { value: 'America/St_Barthelemy', label: 'America/St_Barthelemy' },
    { value: 'America/St_Johns', label: 'America/St_Johns' },
    { value: 'America/St_Kitts', label: 'America/St_Kitts' },
    { value: 'America/St_Lucia', label: 'America/St_Lucia' },
    { value: 'America/St_Thomas', label: 'America/St_Thomas' },
    { value: 'America/St_Vincent', label: 'America/St_Vincent' },
    { value: 'America/Swift_Current', label: 'America/Swift_Current' },
    { value: 'America/Tegucigalpa', label: 'America/Tegucigalpa' },
    { value: 'America/Thule', label: 'America/Thule' },
    { value: 'America/Thunder_Bay', label: 'America/Thunder_Bay' },
    { value: 'America/Tijuana', label: 'America/Tijuana' },
    { value: 'America/Toronto', label: 'America/Toronto' },
    { value: 'America/Tortola', label: 'America/Tortola' },
    { value: 'America/Vancouver', label: 'America/Vancouver' },
    { value: 'America/Whitehorse', label: 'America/Whitehorse' },
    { value: 'America/Winnipeg', label: 'America/Winnipeg' },
    { value: 'America/Yakutat', label: 'America/Yakutat' },
    { value: 'America/Yellowknife', label: 'America/Yellowknife' },
    { value: 'Antarctica/Casey', label: 'Antarctica/Casey' },
    { value: 'Antarctica/Davis', label: 'Antarctica/Davis' },
    { value: 'Antarctica/DumontDUrville', label: 'Antarctica/DumontDUrville' },
    { value: 'Antarctica/Macquarie', label: 'Antarctica/Macquarie' },
    { value: 'Antarctica/Mawson', label: 'Antarctica/Mawson' },
    { value: 'Antarctica/McMurdo', label: 'Antarctica/McMurdo' },
    { value: 'Antarctica/Palmer', label: 'Antarctica/Palmer' },
    { value: 'Antarctica/Rothera', label: 'Antarctica/Rothera' },
    { value: 'Antarctica/Syowa', label: 'Antarctica/Syowa' },
    { value: 'Antarctica/Troll', label: 'Antarctica/Troll' },
    { value: 'Antarctica/Vostok', label: 'Antarctica/Vostok' },
    { value: 'Arctic/Longyearbyen', label: 'Arctic/Longyearbyen' },
    { value: 'Asia/Aden', label: 'Asia/Aden' },
    { value: 'Asia/Almaty', label: 'Asia/Almaty' },
    { value: 'Asia/Amman', label: 'Asia/Amman' },
    { value: 'Asia/Anadyr', label: 'Asia/Anadyr' },
    { value: 'Asia/Aqtau', label: 'Asia/Aqtau' },
    { value: 'Asia/Aqtobe', label: 'Asia/Aqtobe' },
    { value: 'Asia/Ashgabat', label: 'Asia/Ashgabat' },
    { value: 'Asia/Atyrau', label: 'Asia/Atyrau' },
    { value: 'Asia/Baghdad', label: 'Asia/Baghdad' },
    { value: 'Asia/Bahrain', label: 'Asia/Bahrain' },
    { value: 'Asia/Baku', label: 'Asia/Baku' },
    { value: 'Asia/Bangkok', label: 'Asia/Bangkok' },
    { value: 'Asia/Barnaul', label: 'Asia/Barnaul' },
    { value: 'Asia/Beirut', label: 'Asia/Beirut' },
    { value: 'Asia/Bishkek', label: 'Asia/Bishkek' },
    { value: 'Asia/Brunei', label: 'Asia/Brunei' },
    { value: 'Asia/Calcutta', label: 'Asia/Calcutta' },
    { value: 'Asia/Chita', label: 'Asia/Chita' },
    { value: 'Asia/Choibalsan', label: 'Asia/Choibalsan' },
    { value: 'Asia/Colombo', label: 'Asia/Colombo' },
    { value: 'Asia/Damascus', label: 'Asia/Damascus' },
    { value: 'Asia/Dhaka', label: 'Asia/Dhaka' },
    { value: 'Asia/Dili', label: 'Asia/Dili' },
    { value: 'Asia/Dubai', label: 'Asia/Dubai' },
    { value: 'Asia/Dushanbe', label: 'Asia/Dushanbe' },
    { value: 'Asia/Famagusta', label: 'Asia/Famagusta' },
    { value: 'Asia/Gaza', label: 'Asia/Gaza' },
    { value: 'Asia/Hebron', label: 'Asia/Hebron' },
    { value: 'Asia/Hong_Kong', label: 'Asia/Hong_Kong' },
    { value: 'Asia/Hovd', label: 'Asia/Hovd' },
    { value: 'Asia/Irkutsk', label: 'Asia/Irkutsk' },
    { value: 'Asia/Jakarta', label: 'Asia/Jakarta' },
    { value: 'Asia/Jayapura', label: 'Asia/Jayapura' },
    { value: 'Asia/Jerusalem', label: 'Asia/Jerusalem' },
    { value: 'Asia/Kabul', label: 'Asia/Kabul' },
    { value: 'Asia/Kamchatka', label: 'Asia/Kamchatka' },
    { value: 'Asia/Karachi', label: 'Asia/Karachi' },
    { value: 'Asia/Katmandu', label: 'Asia/Katmandu' },
    { value: 'Asia/Khandyga', label: 'Asia/Khandyga' },
    { value: 'Asia/Krasnoyarsk', label: 'Asia/Krasnoyarsk' },
    { value: 'Asia/Kuala_Lumpur', label: 'Asia/Kuala_Lumpur' },
    { value: 'Asia/Kuching', label: 'Asia/Kuching' },
    { value: 'Asia/Kuwait', label: 'Asia/Kuwait' },
    { value: 'Asia/Macau', label: 'Asia/Macau' },
    { value: 'Asia/Magadan', label: 'Asia/Magadan' },
    { value: 'Asia/Makassar', label: 'Asia/Makassar' },
    { value: 'Asia/Manila', label: 'Asia/Manila' },
    { value: 'Asia/Muscat', label: 'Asia/Muscat' },
    { value: 'Asia/Nicosia', label: 'Asia/Nicosia' },
    { value: 'Asia/Novokuznetsk', label: 'Asia/Novokuznetsk' },
    { value: 'Asia/Novosibirsk', label: 'Asia/Novosibirsk' },
    { value: 'Asia/Omsk', label: 'Asia/Omsk' },
    { value: 'Asia/Oral', label: 'Asia/Oral' },
    { value: 'Asia/Phnom_Penh', label: 'Asia/Phnom_Penh' },
    { value: 'Asia/Pontianak', label: 'Asia/Pontianak' },
    { value: 'Asia/Pyongyang', label: 'Asia/Pyongyang' },
    { value: 'Asia/Qatar', label: 'Asia/Qatar' },
    { value: 'Asia/Qyzylorda', label: 'Asia/Qyzylorda' },
    { value: 'Asia/Rangoon', label: 'Asia/Rangoon' },
    { value: 'Asia/Riyadh', label: 'Asia/Riyadh' },
    { value: 'Asia/Samarkand', label: 'Asia/Samarkand' },
    { value: 'Asia/Seoul', label: 'Asia/Seoul' },
    { value: 'Asia/Shanghai', label: 'Asia/Shanghai' },
    { value: 'Asia/Singapore', label: 'Asia/Singapore' },
    { value: 'Asia/Srednekolymsk', label: 'Asia/Srednekolymsk' },
    { value: 'Asia/Taipei', label: 'Asia/Taipei' },
    { value: 'Asia/Tashkent', label: 'Asia/Tashkent' },
    { value: 'Asia/Tbilisi', label: 'Asia/Tbilisi' },
    { value: 'Asia/Tehran', label: 'Asia/Tehran' },
    { value: 'Asia/Thimphu', label: 'Asia/Thimphu' },
    { value: 'Asia/Tokyo', label: 'Asia/Tokyo' },
    { value: 'Asia/Tomsk', label: 'Asia/Tomsk' },
    { value: 'Asia/Ulaanbaatar', label: 'Asia/Ulaanbaatar' },
    { value: 'Asia/Urumqi', label: 'Asia/Urumqi' },
    { value: 'Asia/Ust-Nera', label: 'Asia/Ust-Nera' },
    { value: 'Asia/Vientiane', label: 'Asia/Vientiane' },
    { value: 'Asia/Vladivostok', label: 'Asia/Vladivostok' },
    { value: 'Asia/Yakutsk', label: 'Asia/Yakutsk' },
    { value: 'Asia/Yekaterinburg', label: 'Asia/Yekaterinburg' },
    { value: 'Asia/Yerevan', label: 'Asia/Yerevan' },
    { value: 'Atlantic/Azores', label: 'Atlantic/Azores' },
    { value: 'Atlantic/Bermuda', label: 'Atlantic/Bermuda' },
    { value: 'Atlantic/Canary', label: 'Atlantic/Canary' },
    { value: 'Atlantic/Cape_Verde', label: 'Atlantic/Cape_Verde' },
    { value: 'Atlantic/Faroe', label: 'Atlantic/Faroe' },
    { value: 'Atlantic/Madeira', label: 'Atlantic/Madeira' },
    { value: 'Atlantic/Reykjavik', label: 'Atlantic/Reykjavik' },
    { value: 'Atlantic/South_Georgia', label: 'Atlantic/South_Georgia' },
    { value: 'Atlantic/St_Helena', label: 'Atlantic/St_Helena' },
    { value: 'Atlantic/Stanley', label: 'Atlantic/Stanley' },
    { value: 'Australia/Adelaide', label: 'Australia/Adelaide' },
    { value: 'Australia/Brisbane', label: 'Australia/Brisbane' },
    { value: 'Australia/Broken_Hill', label: 'Australia/Broken_Hill' },
    { value: 'Australia/Currie', label: 'Australia/Currie' },
    { value: 'Australia/Darwin', label: 'Australia/Darwin' },
    { value: 'Australia/Eucla', label: 'Australia/Eucla' },
    { value: 'Australia/Hobart', label: 'Australia/Hobart' },
    { value: 'Australia/Lindeman', label: 'Australia/Lindeman' },
    { value: 'Australia/Lord_Howe', label: 'Australia/Lord_Howe' },
    { value: 'Australia/Melbourne', label: 'Australia/Melbourne' },
    { value: 'Australia/Perth', label: 'Australia/Perth' },
    { value: 'Australia/Sydney', label: 'Australia/Sydney' },
    { value: 'Europe/Amsterdam', label: 'Europe/Amsterdam' },
    { value: 'Europe/Andorra', label: 'Europe/Andorra' },
    { value: 'Europe/Astrakhan', label: 'Europe/Astrakhan' },
    { value: 'Europe/Athens', label: 'Europe/Athens' },
    { value: 'Europe/Belgrade', label: 'Europe/Belgrade' },
    { value: 'Europe/Berlin', label: 'Europe/Berlin' },
    { value: 'Europe/Bratislava', label: 'Europe/Bratislava' },
    { value: 'Europe/Brussels', label: 'Europe/Brussels' },
    { value: 'Europe/Bucharest', label: 'Europe/Bucharest' },
    { value: 'Europe/Budapest', label: 'Europe/Budapest' },
    { value: 'Europe/Busingen', label: 'Europe/Busingen' },
    { value: 'Europe/Chisinau', label: 'Europe/Chisinau' },
    { value: 'Europe/Copenhagen', label: 'Europe/Copenhagen' },
    { value: 'Europe/Dublin', label: 'Europe/Dublin' },
    { value: 'Europe/Gibraltar', label: 'Europe/Gibraltar' },
    { value: 'Europe/Guernsey', label: 'Europe/Guernsey' },
    { value: 'Europe/Helsinki', label: 'Europe/Helsinki' },
    { value: 'Europe/Isle_of_Man', label: 'Europe/Isle_of_Man' },
    { value: 'Europe/Istanbul', label: 'Europe/Istanbul' },
    { value: 'Europe/Jersey', label: 'Europe/Jersey' },
    { value: 'Europe/Kaliningrad', label: 'Europe/Kaliningrad' },
    { value: 'Europe/Kiev', label: 'Europe/Kiev' },
    { value: 'Europe/Kirov', label: 'Europe/Kirov' },
    { value: 'Europe/Lisbon', label: 'Europe/Lisbon' },
    { value: 'Europe/Ljubljana', label: 'Europe/Ljubljana' },
    { value: 'Europe/London', label: 'Europe/London' },
    { value: 'Europe/Luxembourg', label: 'Europe/Luxembourg' },
    { value: 'Europe/Madrid', label: 'Europe/Madrid' },
    { value: 'Europe/Malta', label: 'Europe/Malta' },
    { value: 'Europe/Mariehamn', label: 'Europe/Mariehamn' },
    { value: 'Europe/Minsk', label: 'Europe/Minsk' },
    { value: 'Europe/Monaco', label: 'Europe/Monaco' },
    { value: 'Europe/Moscow', label: 'Europe/Moscow' },
    { value: 'Europe/Oslo', label: 'Europe/Oslo' },
    { value: 'Europe/Paris', label: 'Europe/Paris' },
    { value: 'Europe/Podgorica', label: 'Europe/Podgorica' },
    { value: 'Europe/Prague', label: 'Europe/Prague' },
    { value: 'Europe/Riga', label: 'Europe/Riga' },
    { value: 'Europe/Rome', label: 'Europe/Rome' },
    { value: 'Europe/Samara', label: 'Europe/Samara' },
    { value: 'Europe/San_Marino', label: 'Europe/San_Marino' },
    { value: 'Europe/Sarajevo', label: 'Europe/Sarajevo' },
    { value: 'Europe/Saratov', label: 'Europe/Saratov' },
    { value: 'Europe/Simferopol', label: 'Europe/Simferopol' },
    { value: 'Europe/Skopje', label: 'Europe/Skopje' },
    { value: 'Europe/Sofia', label: 'Europe/Sofia' },
    { value: 'Europe/Stockholm', label: 'Europe/Stockholm' },
    { value: 'Europe/Tallinn', label: 'Europe/Tallinn' },
    { value: 'Europe/Tirane', label: 'Europe/Tirane' },
    { value: 'Europe/Ulyanovsk', label: 'Europe/Ulyanovsk' },
    { value: 'Europe/Uzhgorod', label: 'Europe/Uzhgorod' },
    { value: 'Europe/Vaduz', label: 'Europe/Vaduz' },
    { value: 'Europe/Vatican', label: 'Europe/Vatican' },
    { value: 'Europe/Vienna', label: 'Europe/Vienna' },
    { value: 'Europe/Vilnius', label: 'Europe/Vilnius' },
    { value: 'Europe/Volgograd', label: 'Europe/Volgograd' },
    { value: 'Europe/Warsaw', label: 'Europe/Warsaw' },
    { value: 'Europe/Zagreb', label: 'Europe/Zagreb' },
    { value: 'Europe/Zaporozhye', label: 'Europe/Zaporozhye' },
    { value: 'Europe/Zurich', label: 'Europe/Zurich' },
    { value: 'Indian/Antananarivo', label: 'Indian/Antananarivo' },
    { value: 'Indian/Chagos', label: 'Indian/Chagos' },
    { value: 'Indian/Christmas', label: 'Indian/Christmas' },
    { value: 'Indian/Cocos', label: 'Indian/Cocos' },
    { value: 'Indian/Comoro', label: 'Indian/Comoro' },
    { value: 'Indian/Kerguelen', label: 'Indian/Kerguelen' },
    { value: 'Indian/Mahe', label: 'Indian/Mahe' },
    { value: 'Indian/Maldives', label: 'Indian/Maldives' },
    { value: 'Indian/Mauritius', label: 'Indian/Mauritius' },
    { value: 'Indian/Mayotte', label: 'Indian/Mayotte' },
    { value: 'Indian/Reunion', label: 'Indian/Reunion' },
    { value: 'Pacific/Apia', label: 'Pacific/Apia' },
    { value: 'Pacific/Auckland', label: 'Pacific/Auckland' },
    { value: 'Pacific/Bougainville', label: 'Pacific/Bougainville' },
    { value: 'Pacific/Chatham', label: 'Pacific/Chatham' },
    { value: 'Pacific/Easter', label: 'Pacific/Easter' },
    { value: 'Pacific/Efate', label: 'Pacific/Efate' },
    { value: 'Pacific/Enderbury', label: 'Pacific/Enderbury' },
    { value: 'Pacific/Fakaofo', label: 'Pacific/Fakaofo' },
    { value: 'Pacific/Fiji', label: 'Pacific/Fiji' },
    { value: 'Pacific/Funafuti', label: 'Pacific/Funafuti' },
    { value: 'Pacific/Galapagos', label: 'Pacific/Galapagos' },
    { value: 'Pacific/Gambier', label: 'Pacific/Gambier' },
    { value: 'Pacific/Guadalcanal', label: 'Pacific/Guadalcanal' },
    { value: 'Pacific/Guam', label: 'Pacific/Guam' },
    { value: 'Pacific/Honolulu', label: 'Pacific/Honolulu' },
    { value: 'Pacific/Johnston', label: 'Pacific/Johnston' },
    { value: 'Pacific/Kiritimati', label: 'Pacific/Kiritimati' },
    { value: 'Pacific/Kosrae', label: 'Pacific/Kosrae' },
    { value: 'Pacific/Kwajalein', label: 'Pacific/Kwajalein' },
    { value: 'Pacific/Majuro', label: 'Pacific/Majuro' },
    { value: 'Pacific/Marquesas', label: 'Pacific/Marquesas' },
    { value: 'Pacific/Midway', label: 'Pacific/Midway' },
    { value: 'Pacific/Nauru', label: 'Pacific/Nauru' },
    { value: 'Pacific/Niue', label: 'Pacific/Niue' },
    { value: 'Pacific/Norfolk', label: 'Pacific/Norfolk' },
    { value: 'Pacific/Noumea', label: 'Pacific/Noumea' },
    { value: 'Pacific/Pago_Pago', label: 'Pacific/Pago_Pago' },
    { value: 'Pacific/Palau', label: 'Pacific/Palau' },
    { value: 'Pacific/Pitcairn', label: 'Pacific/Pitcairn' },
    { value: 'Pacific/Ponape', label: 'Pacific/Ponape' },
    { value: 'Pacific/Port_Moresby', label: 'Pacific/Port_Moresby' },
    { value: 'Pacific/Rarotonga', label: 'Pacific/Rarotonga' },
    { value: 'Pacific/Saipan', label: 'Pacific/Saipan' },
    { value: 'Pacific/Tahiti', label: 'Pacific/Tahiti' },
    { value: 'Pacific/Tarawa', label: 'Pacific/Tarawa' },
    { value: 'Pacific/Tongatapu', label: 'Pacific/Tongatapu' },
    { value: 'Pacific/Truk', label: 'Pacific/Truk' },
    { value: 'Pacific/Wake', label: 'Pacific/Wake' },
    { value: 'Pacific/Wallis', label: 'Pacific/Wallis' },
];